image:
  repository: cosmic-blanket/licensing-service
  tag: latest
  pullPolicy: IfNotPresent
service:
  port: 8081
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
env: {}
