quarkus.http.port=8082
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/cosmic_blanket
quarkus.datasource.username=cosmic
quarkus.datasource.password=cosmic
quarkus.hibernate-orm.database.default-schema=vital_records
quarkus.hibernate-orm.database.generation=none
quarkus.flyway.migrate-at-start=true
quarkus.flyway.schemas=vital_records
quarkus.flyway.locations=classpath:db/migration

quarkus.smallrye-openapi.info-title=Vital Records Service API
quarkus.smallrye-openapi.info-version=1.0.0

# Kafka messaging
mp.messaging.outgoing.documents-changed.connector=smallrye-kafka
mp.messaging.outgoing.documents-changed.topic=documents.changed
mp.messaging.outgoing.documents-changed.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer

mp.messaging.outgoing.service-notifications.connector=smallrye-kafka
mp.messaging.outgoing.service-notifications.topic=services.notifications
mp.messaging.outgoing.service-notifications.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
