apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-env-config
data:
  env-config.js: |
    window.__COSMIC_CONFIG__ = {
      KEYCLOAK_URL: "https://keycloak-cosmic-blanket.apps.wz405duy.eastus.aroapp.io/realms/nova",
    };
