apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ include "ai-service.fullname" . }}
  labels:
    {{- include "ai-service.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      labels:
        {{- include "ai-service.labels" . | nindent 8 }}
    spec:
      containers:
        - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "ai-service.fullname" . }}-config
            - secretRef:
                name: {{ include "ai-service.fullname" . }}-secret
                optional: true
