apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - frontend-nginx-cm.yaml
  - frontend-env-cm.yaml
  - gateway-deployment.yaml
  - gateway-service.yaml
  - licensing-deployment.yaml
  - licensing-service.yaml
  - vital-records-deployment.yaml
  - vital-records-service.yaml
  - property-tax-deployment.yaml
  - property-tax-service.yaml
  - ai-deployment.yaml
  - ai-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - frontend-route.yaml

labels:
  - pairs:
      app.kubernetes.io/managed-by: argocd
