apiVersion: v1
kind: Service
metadata:
  name: vital-records-service
  labels:
    app: vital-records-service
spec:
  selector:
    app: vital-records-service
  ports:
    - port: 8080
      targetPort: 8080
