apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patches/frontend-env.yaml
  - path: patches/gateway-env.yaml
  - path: patches/resources.yaml
